package com.example.yaoyufei.a1807_qimoa.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.a1807_qimoa.bean.DailyNewsDbBeanDao;

import com.example.yaoyufei.a1807_qimoa.dao.DailyNewsDbBeanDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dailyNewsDbBeanDaoDaoConfig;

    private final DailyNewsDbBeanDaoDao dailyNewsDbBeanDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dailyNewsDbBeanDaoDaoConfig = daoConfigMap.get(DailyNewsDbBeanDaoDao.class).clone();
        dailyNewsDbBeanDaoDaoConfig.initIdentityScope(type);

        dailyNewsDbBeanDaoDao = new DailyNewsDbBeanDaoDao(dailyNewsDbBeanDaoDaoConfig, this);

        registerDao(DailyNewsDbBeanDao.class, dailyNewsDbBeanDaoDao);
    }
    
    public void clear() {
        dailyNewsDbBeanDaoDaoConfig.clearIdentityScope();
    }

    public DailyNewsDbBeanDaoDao getDailyNewsDbBeanDaoDao() {
        return dailyNewsDbBeanDaoDao;
    }

}
